auto: true
permalink: /blog/:year/:month/:title/
url: http://www.colaborativa.eu

titulo: Colaborativa
subtitulo: { es: Estrategias y herramientas para transformar ciudades, en: Strategies and tools for transforming cities}
navegacion: { es: Navegación principal, en: Main navigation}
navegacion-blog: { es: Blog, en: Blog}
navegacion-proyectos: { es: Proyectos, en: Projects}
navegacion-equipo: { es: Equipo, en: Team}
navegacion-herramientas: { es: Herramientas, en: Tools}
navegacion-codigo: { es: Código, en: Code}

footer-mapa: { es: Mapa, en: Map}
footer-copyleft: { es: Algunos derechos reservados, en: Some rights reserved}
enlaces-sociales-facebook: { url: http://www.facebook.com/pages/Colaborativa/129415973823832, es: Estamos en Facebook, en: We are in Facebook}
enlaces-sociales-twitter: { url: http://twitter.com/colaborativaeu, es: Síguenos en Twitter, en: Follow us in Twitter}
enlaces-sociales-flickr: { url: http://www.flickr.com/photos/50381188@N06/, es: Nuestras fotos en Flickr, en: Our pictures in Flickr}
enlaces-sociales-youtube: { url: http://www.youtube.com/user/colaborativaeu, es: Nuestros videos en YouTube, en: Our videos in YouTube}
enlaces-sociales-issuu: { url: http://www.issuu.com/colaborativa, es: Nuestros documentos en Issuu, en: Our documents in Issuu}

listado-colaborativos-titulo: { es: Colaborativos, en: Colaborativos}
listado-colaborativos-subtitulo: { es: ¿Quiénes somos?, en: Who we are?}

listado-colaboradores-titulo: { es: Colaboradores, en: Colaboradores}
listado-colaboradores-subtitulo: { es: ¿Con quién colaboramos?, en: Who we work with?}

listado-articulos-autor-titulo: { es: Artículos de este autor, en: Articles from this author }
listado-articulos-autor-subtitulo: { es: en nuestro blog, en: in our blog}

listado-articulos-categorias-titulo: { es: Algunos proyectos, en: Some projects}
listado-articulos-categorias-subtitulo: { es: relacionados con este artículo, en: related with this article}

listado-articulos-relacionados-titulo: { es: Otros artículos en nuestro blog, en: Other articles in our blog}
listado-articulos-relacionados-subtitulo: { es: que podrían interesarte, en: that may interest you}

listado-articulos-proyecto-titulo: { es: Últimos 5 artículos en el Blog, en: Last 5 articles}
listado-articulos-proyecto-subtitulo: { es: sabre este proyecto, en: about this project}

listado-proyectos-categorias-titulo: { es: ¿Qué hacemos?, en: What we do }
listado-proyectos-colaboradores-titulo: { es: Colaboradores, en: Colaboradores}
listado-proyectos-colaboradores-subtitulo: { es: en este proyecto colaboramos con, en: we work with}


listado-blog-categorias-titulo: { es: Ver artículos, en: List articles}
listado-blog-categorias-subtitulo: { es: por categoría, en: by category}

listado-enlaces-prensa-titulo: { es: Referencias en medios, en: References en medios}
listado-enlaces-prensa-subtitulo: { es: Sobre este proyecto, en: in media}

listado-reacciones-titulo: { es: Reacciones en Twitter, en: Twitter's reactions}
listado-reacciones-subtitulo: { es: , en:  }

listado-reacciones-articulo-texto: { es: Comenta este artículo con nosotros @colaborativaeu, en: Comment this article with us @colaborativaeu }
listado-reacciones-proyecto-texto: { es: Comenta este proyecto con nosotros @colaborativaeu, en: Comment this project with us @colaborativaeu }

inline-articulos: { es: artículo, en: article}
inline-en: { es: en, en: in}
inline-por: { es: por, en: by}
inline-y: { es: y, en: "&"}
inline-proyectos: { es: proyecto, en: project}
inline-auto-traduccion: { es: traducción automática, en: automated translation }
